version: '3.5'

services:
  postgres:
    container_name: postgres_taskManagerdb
    image: postgres:13.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskManagerdb
      PGDATA: /data/postgres



