# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches:
    - main
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Echo date
      run: date      
